name: Nasa test Project
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
job:
  build:
    runs-on: ubantu-latest
    steps: 
      - uses: actions/checkout@v2
      name: Use Node.js version 16
      - uses: actions/setup-nodes@v2
        with: 
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client
